REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_donation(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.advance_donation_status(UUID, TEXT) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.donation_parties(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.my_dashboard_stats() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.network_impact_stats() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_donation(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.advance_donation_status(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.donation_parties(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_dashboard_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.network_impact_stats() TO authenticated;